### ISSUE TITLE
Failed to parse SourceMap

### ISSUE THREAD

**Issue by damienbrz** [nkbt/react-page-click#25]
I'm getting the following error as soon as I require the component into my React app.

```
Failed to parse SourceMap: http://localhost:3000/index.js.map
```

![screen shot 2016-09-05 at 9 15 53 pm](https://cloud.githubusercontent.com/assets/229829/18246265/f3fe77c8-73ad-11e6-9aeb-ce8429f75d3f.png)

**Comment by nkbt** [comment]
Hi 👋

What browser is it?
What lib version?
How did you install it?

**Comment by damienbrz** [comment]
I'm on a MacBook Air with OS 10.11.6
Running Chrome Version 52.0.2743.116 (64-bit)
I run the following command to install it:
```
npm i --save react-page-click
```

**Comment by nkbt** [comment]
Hm, looks similar to mine, have not seen it before... I will double-check.
Most likely there was some sneaky dep. update

**Comment by jbhatab** [comment]
getting something similar. 

<img width="902" alt="screen shot 2016-09-11 at 6 45 39 pm" src="https://cloud.githubusercontent.com/assets/2458718/18422447/fdfc353e-784f-11e6-98f5-3a51c1689ebc.png">

**Comment by nkbt** [comment]
Thanks I'll see what I can do

**Comment by nkbt** [comment]
Fixed by https://github.com/nkbt/react-page-click/pull/38

Will publish new version asap
