### ISSUE TITLE
React v15.5 deprecating React.createClass

### ISSUE THREAD

**Issue by aribronstein** [nkbt/react-page-click#32]
I was upgrading my React version and now am receiving this error:
Warning: ReactPageClick: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

**Comment by nkbt** [comment]
Need to switch to `prop-types` and `create-react-class`. PR welcomed!
