### ISSUE TITLE
No more draggable events after using it

### ISSUE THREAD

**Issue by bigardone** [nkbt/react-page-click#7]
Hi there!
I'm using your awesome component-wrapper and everything seems to work fine until I try to add any drag and drop functionality or library. I looks like drag events are not fired any more. If I remove the PageClick wrapper component then drag events start working again.
Is there a configuration prop or whatever to prevent this?
Thank you very much in advance :)

**Comment by nkbt** [comment]
Hi, @bigardone, thanks for checking out PageClick =).
That might be the case of using `onClick` handler on a container element (internally at PageClick). I am not 100% sure if that is true, it would help a lot if you clone http://codepen.io/nkbt/pen/JYEPVQ and add some of your code inside to reproduce the issue.

Cheers!

**Comment by bigardone** [comment]
Hey @nkbt , I'm about to share the project on Github where I'm using it. As soon as I do it, I can link here the exact place where I have the issue and explain a bit more about the implementation.

Cheers!

**Comment by nkbt** [comment]
That's awesome, thank you

**Comment by nkbt** [comment]
Hi, @bigardone!

Any news on this one? I am about to close the issue and want to be sure everything is ok here


Thanks

**Comment by bigardone** [comment]
Hi, @nkbt!
Sorry, I totally forgot about this. I haven't had this issue again so feel free to close it.
Cheers!
